export interface CSVRecord {
  Lookup: string;
  Player: string;
  'HP url': string;
  'QM MMR': string;
  'SL MMR': string;
  'QM Games': string;
  'SL Games': string;
  MMR: string;
  'Win %': string;
  Games: string;
  Takedowns: string;
  Kills: string;
  Assists: string;
  Deaths: string;
  'Kill Participation': string;
  KDA: string;
  'Highest Kill Streak': string;
  Vengeances: string;
  'Time Dead': string;
  'Time Dead %': string;
  'Deaths While Outnumbered': string;
  Escapes: string;
  'Team Fight Escapes': string;
  'Hero Damage': string;
  DPM: string;
  'Physical Damage': string;
  'Ability Damage': string;
  'Damage per Death': string;
  'Team Fight Hero Damage': string;
  'Siege Damage': string;
  'Structure Damage': string;
  'Minion Damage': string;
  'Summon Damage': string;
  'Creep Damage': string;
  Healing: string;
  HPM: string;
  'Healing per Death': string;
  'Team Fight Healing': string;
  'Self Healing': string;
  'Allied Shields': string;
  'Clutch Heals': string;
  'Damage Taken': string;
  'Damage Soaked': string;
  'Damage Taken per Death': string;
  'Team Fight Damage Taken': string;
  'CC Time': string;
  'Root Time': string;
  'Silence Time': string;
  'Stun Time': string;
  'Time on Fire': string;
  'XP Contribution': string;
  XPM: string;
  'Merc Camp Captures': string;
  'Watch Tower Captures': string;
  Aces: string;
  Wipes: string;
  '% of Game with Level Adv.': string;
  '% of Game with Hero Adv.': string;
  'Passive XP/Second': string;
  'Passive XP Gained': string;
  'Altar Damage Done': string;
  'Damage to Immortal': string;
  'Dragon Knights Captured': string;
  'Shrines Captured': string;
  'Dubloons Held At End': string;
  'Dubloons Turned In': string;
  'Skulls Collected': string;
  'Shrine Minion Damage': string;
  'Plant Damage': string;
  'Seeds Collected': string;
  'Garden Seeds Collected': string;
  'Gems Turned In': string;
  'Nuke Damage': string;
  'Curse Damage': string;
  'Time On Temple': string;
  'Damage Done to Zerg': string;
  'Cage Unlocks Interrupted': string;
  'Hero Pool': string;
  'Damage Ratio': string;
  '% of Team Damage': string;
  '% of Team Damage Taken': string;
  '% of Team Damage Healed': string;
  '% of Time Slow CC': string;
  '% of Time Non-Slow CC': string;
  Votes: string;
  Awards: string;
  'Award %': string;
  MVP: string;
  'MVP %': string;
  Bsteps: string;
  'Bstep TD': string;
  'Bstep Deaths': string;
  Taunts: string;
  'Taunt TD': string;
  'Taunt Deaths': string;
  Sprays: string;
  'Spray TD': string;
  'Spray Deaths': string;
  Dances: string;
  'Dance TD': string;
  'Dance Deaths': string;
}
